/**
 * UAT-7 P3-22 verification — Calendar cross-year edge case
 *
 * Asserts that bill occurrences generated by `getBillsForPeriod` render
 * correctly across the Dec → Jan boundary without date drift.
 *
 * Run: npx tsx uat-reports/verify-p3-22-calendar-crossyear.ts
 */

import { getBillsForPeriod, getNextBillOccurrence } from "../server/lib/financial-engine/bills";
import type { Bill } from "../shared/schema";

function assert(cond: unknown, msg: string): void {
  if (!cond) {
    console.error(`FAIL: ${msg}`);
    process.exitCode = 1;
  } else {
    console.log(`PASS: ${msg}`);
  }
}

function fmt(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// Test bill: monthly recurring on the 28th, starting Nov 2026.
const bill: Bill = {
  id: "test-bill-p3-22",
  userId: "test-user",
  name: "ZZ-QA Year-End Bill",
  amount: "42.00",
  category: "Other",
  dueDay: 28,
  recurrence: "monthly",
  customDates: null,
  notes: null,
  lastNotifiedCycle: null,
  startingBalance: null,
  paymentsRemaining: null,
  startDate: "2026-11-28",
  endDate: null,
  isPaused: "false",
  merchant: null,
  linkedPlaidAccountId: null,
};

console.log("\n=== P3-22 Calendar Cross-Year Edge Case ===\n");

// --- Test 1: getNextBillOccurrence from Dec 1 2026 → should be Dec 28 2026
const fromDec1 = new Date(2026, 11, 1); // Dec = month 11 (0-indexed)
const next1 = getNextBillOccurrence(bill, fromDec1);
assert(next1 !== null, "getNextBillOccurrence(Dec 1 2026) is not null");
assert(next1 && fmt(next1) === "2026-12-28", `next from Dec 1 2026 = ${next1 && fmt(next1)} (expected 2026-12-28)`);

// --- Test 2: getNextBillOccurrence from Dec 29 2026 → should be Jan 28 2027
const fromDec29 = new Date(2026, 11, 29);
const next2 = getNextBillOccurrence(bill, fromDec29);
assert(next2 !== null, "getNextBillOccurrence(Dec 29 2026) is not null");
assert(next2 && fmt(next2) === "2027-01-28", `next from Dec 29 2026 = ${next2 && fmt(next2)} (expected 2027-01-28)`);

// --- Test 3: getNextBillOccurrence from Jan 15 2027 → should be Jan 28 2027
const fromJan15 = new Date(2027, 0, 15);
const next3 = getNextBillOccurrence(bill, fromJan15);
assert(next3 && fmt(next3) === "2027-01-28", `next from Jan 15 2027 = ${next3 && fmt(next3)} (expected 2027-01-28)`);

// --- Test 4: getBillsForPeriod across the boundary — Dec 1 2026 to Apr 30 2027
// Should produce 5 occurrences, all on the 28th: Dec 28 2026, Jan 28 2027, Feb 28 2027, Mar 28 2027, Apr 28 2027.
const periodStart = new Date(2026, 11, 1);
const periodEnd = new Date(2027, 3, 30);
const occurrences = getBillsForPeriod([bill], periodStart, periodEnd);

assert(occurrences.length === 5, `period Dec 1 2026 – Apr 30 2027 produces 5 occurrences (got ${occurrences.length})`);

const expected = ["2026-12-28", "2027-01-28", "2027-02-28", "2027-03-28", "2027-04-28"];
for (let i = 0; i < expected.length; i++) {
  const actual = occurrences[i] ? fmt(occurrences[i].dueDate) : "(missing)";
  assert(actual === expected[i], `occurrence[${i}] = ${actual} (expected ${expected[i]})`);
}

// --- Test 5: Every occurrence is on the 28th (no drift)
const allOn28 = occurrences.every((o) => o.dueDate.getDate() === 28);
assert(allOn28, "every occurrence in the period is on the 28th");

// --- Test 6: No duplicate occurrences on the same day (would indicate a bug)
const dateStrings = occurrences.map((o) => fmt(o.dueDate));
const uniqueDates = new Set(dateStrings);
assert(uniqueDates.size === dateStrings.length, "no duplicate occurrence dates in the period");

// --- Test 7: Year transition — Dec 2026 occurrence has year=2026, Jan 2027 has year=2027
const decOccurrence = occurrences.find((o) => o.dueDate.getMonth() === 11);
const janOccurrence = occurrences.find((o) => o.dueDate.getMonth() === 0);
assert(decOccurrence && decOccurrence.dueDate.getFullYear() === 2026, "December occurrence has year 2026");
assert(janOccurrence && janOccurrence.dueDate.getFullYear() === 2027, "January occurrence has year 2027");

console.log("\n=== Summary ===");
if (process.exitCode === 1) {
  console.log("P3-22: FAILED — see failures above.");
} else {
  console.log("P3-22: ALL PASSED — calendar handles cross-year boundary correctly.");
}
